### ISSUE TITLE
Add Project

### ISSUE THREAD

**Issue by stevegood** [guidokessels/xwing-data#117]
First, thanks for the great data!  I've created a package that exposes the data directory at modules.  I did this more as an experiment but have since come to rely on it in an application I'm currently in development on.  The repo for my "fork" is here: https://github.com/stevegood/xwing-data-module

Enjoy!

**Comment by guidokessels** [comment]
Thanks! Feel free to open a pull and add it to the list.

I've been meaning to add proper module exports to xwing-data for a while but haven't gotten around to it. 

If I may ask, what project are you working on? :)

**Comment by stevegood** [comment]
I'm building a tool that has the basics (collection manager, squad builder, etc) but also has some more advanced things built in (purchase advisor, maneuver simulator, and a little AI for squad build suggestions / analysis)  https://github.com/stevegood/deep_core

**Comment by stevegood** [comment]
PR #118 adds the link.  I may be back to add a link for Deep Core once I have it up and running. 🙃

**Comment by guidokessels** [comment]
Nice, looks promising!
