### ISSUE TITLE
Spelling errors in upgrades.js

### ISSUE THREAD

**Issue by philtomblin** [guidokessels/xwing-data#13]
- [x] Id 10 (Squad Leader) - Ability text - "my" should read "may"
- [x] Id 131 (Bossk) - Ability text - "perfrom" should read "perform"
- [x] Id 137 (Extra Munitions) - Ability text - "euip" should read "equip"
- [x] Id 199 (XX-23 S-Thread Tracers) - Ability text - "aqcuire" should read "acquire"
- [x] Id 237 (R5-P8) - Ability text - "you and the **attack** each" should read "you and the **attacker** each"
- [x] Id 244 (Black One) - Ability text - "1\nenemy" should read "1 enemy" (unclear if this was intended to be a newline character; however, the card does not have a newline character at this location and the presence of the \n causes issues when importing the JSON into MS Excel so would be grateful if you could fix accordingly)

**Comment by guidokessels** [comment]
Thanks a lot! I'll fix it tonight.

**Comment by guidokessels** [comment]
I've fixed them all in https://github.com/guidokessels/xwing-data/commit/62954f11c812f93884a32523feadeae8c0951390

Thanks again. Some of these have been in there for almost 2 years. Can't believe noone noticed :)

**Comment by philtomblin** [comment]
No worries - thanks for the quick turnaround!

Phil

**Comment by philtomblin** [comment]
I've just double-checked the fixes and all are fine, except for one...  The Bossk ability text has been changed to "perfom" - it should read "perform" :)  Please could you re-fix?

**Comment by guidokessels** [comment]
Whops. I'll fix it tonight.

**Comment by guidokessels** [comment]
Also, I'm interested to hear what kind of project you're working on :)

**Comment by guidokessels** [comment]
@philtomblin It's fixed now. I'll create a new release.
