### ISSUE TITLE
Dual-card pilot image storage is inconsistent

### ISSUE THREAD

**Issue by jmthompson2015** [guidokessels/xwing-data#140]
The dual-card huge pilots are stored like this:

xwing-data/images/pilots/Galactic Empire/Raider-class Corvette/raider-class-corv-aft.png
xwing-data/images/pilots/Galactic Empire/Raider-class Corvette/raider-class-corv-fore.png

and

xwing-data/images/pilots/Rebel Alliance/CR90 Corvette (Aft)/cr90-corvette-aft.png
xwing-data/images/pilots/Rebel Alliance/CR90 Corvette (Fore)/cr90-corvette-fore.png

The Raider has two images in the same directory; the CR90 has one image in each of two directories. Can these be made consistent?

**Comment by guidokessels** [comment]
I prefer having them in a single directory. These multi-section ships should be treated as a single ship. That will need some changes in the json structure, and I haven't figured out yet how I want to do it. But for now lets make the image path consistent.

**Comment by guidokessels** [comment]
Fixed in #143.
