### ISSUE TITLE
Kanan Jarrus crew image filename is misspelled

### ISSUE THREAD

**Issue by jmthompson2015** [guidokessels/xwing-data#141]
The Kanan Jarrus crew upgrade file is:

xwing-data/images/upgrades/Crew/**kannan**-jarrus.png

Should be:

xwing-data/images/upgrades/Crew/**kanan**-jarrus.png

**Comment by guidokessels** [comment]
Well spotted. I'm not near a computer right now. Feel free to make a PR, or I can do it later today or tomorrow.

**Comment by jmthompson2015** [comment]
No problem, no hurry. Just trying to help.

**Comment by guidokessels** [comment]
This is now fixed. Thanks!
