### ISSUE TITLE
suggestion: merge "actions" and "grants" in upgrades.js

### ISSUE THREAD

**Issue by beeglebug** [guidokessels/xwing-data#16]
At the moment it's only the Millenium Falcon title which has an "actions" property, it feels like this would be better situated inside the existing "grants" array.

Grants already supports multiple types of grant, they all have a key of "slot" at the moment, so it could go in with a key of "action" instead.

To make parsing that array a bit easier, I would then suggest changing grants to something like:

```
"grants": [
  {
    "type": "slot",
    "name": "Bomb"
  }
]
```

Name could be anything though, either an xws string, or id number even.

**Comment by beeglebug** [comment]
I can whip up a PR for this later if you are open to it?

**Comment by guidokessels** [comment]
Hey! The `actions` and `grants` fields are leftovers from when I was building a squad builder. I stopped the project a while ago so I haven't looked at these fields in a while.

I was thinking of removing the fields as I don't use them, and this repo is really only for card data and images. I didn't think anyone was using them.

But this seems sensible, so feel free to make a pull.

**Comment by guidokessels** [comment]
Thanks, I've merged your PR.

I see we're missing the `grants` field for the following cards:
- Sabine Wren
- Sabine's Masterpiece
- Smuggling Compartment
- R2-D6
- Bomb Loadout

I can add them later. 

Any idea how to handle `"Heavy Scyk" Interceptor`? It has a choice of 3 slots. The choice should be made in some kind of squad builder UI which we can't represent here. We could do something like:
```json
{
  "grants": [
    {
      "type": "choice",
      "choices": [
        {
          "type": "slot",
          "name": "Cannon"
        },
        {
          "type": "slot",
          "name": "Missile"
        },
        {
          "type": "slot",
          "name": "Torpedo"
        }
      ]
    }
  ]
}
```

**Comment by beeglebug** [comment]
That seems like a good way of handling it. I'm currently in the early stages of using this repo as the starting point for a squadron builder, so expect a few more issues/PR's as and when I hit stuff down that route!

**Comment by guidokessels** [comment]
Well I've updated the `grants` field for the following cards:
- Engine Upgrade
- Vectored Thrusters
- Sabine (Crew)
- Sabine's Masterpiece
- Smuggling Compartment
- R2-D6
- Bomb Loadout
