### ISSUE TITLE
TIE Aggressor data shouldn't have turret

### ISSUE THREAD

**Issue by jmthompson2015** [guidokessels/xwing-data#175]
In ships.js, the TIE Aggressor entry has:

"firing_arcs": [
      "Front",
      "Turret"
    ],

Should be (I think):

"firing_arcs": [
      "Front"
    ],

**Comment by stevegood** [comment]
Why shouldn't it?  It can equip turrets.

**Comment by guidokessels** [comment]
@jmthompson2015 You are correct. The `Turret` firing arc should only be there if the TIE Aggressor had a PWT, which it doesn't.

@stevegood The Turret _slot_ is in the `slots` field and is different from the Turret `firing_arc`.

**Comment by stevegood** [comment]
I was clearly confused on what the criteria was for being included in the firing_arcs array... 😝
