### ISSUE TITLE
JSON schema

### ISSUE THREAD

**Issue by lvisintini** [guidokessels/xwing-data#18]
Hi guys,

I'm currently writing a [JSON schema](https://spacetelescope.github.io/understanding-json-schema/) for this data.
Is meant to help to make sure the data is formatted consistently and to also act as some sort of documentation on how to make updates to it.

Should I proceed? would something like that be considered for pulling into the repo?

Cheers
lvisintini

**Comment by guidokessels** [comment]
Hey, this is definitely something I'd be interested in. I've thought of doing it myself but never did it as I wasn't sure if anyone else was actually using this repository :)

I'm rethinking some of the fields and structures of the data files for the 1.0 release. This would definitely be something that would be great to include in 1.0!

**Comment by lvisintini** [comment]
Cool. I'm finishing up the work soon and you could comment.
What sort of changes do you have in mind for the 1.0 release? You mentioned a list...

**Comment by guidokessels** [comment]
> What sort of changes do you have in mind for the 1.0 release? You mentioned a list...

I've got a simple list somewhere. One of these days I'll do a proper write-up and make a new issue here on GitHub so everyone can have some input.

**Comment by kingargyle** [comment]
One thing that would be nice to include in the data model, is an abbreviation of the ship, or upgrades.  I'm using the data in XStreamer, and there are times when it would be nice to access a shorter abbreviation for the upgrades in particular.  If we could include that as an optional field in the schemas that would be nice.

**Comment by lvisintini** [comment]
I'll have a look :)

On 21 Nov 2016 2:36 am, "David Carver" <notifications@github.com> wrote:

One thing that would be nice to include in the data model, is an
abbreviation of the ship, or upgrades. I'm using the data in XStreamer, and
there are times when it would be nice to access a shorter abbreviation for
the upgrades in particular. If we could include that as an optional field
in the schemas that would be nice.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/guidokessels/xwing-data/issues/18#issuecomment-261828908>,
or mute the thread

**Comment by lvisintini** [comment]
@kingargyle I like your idea, but for the moment I'm only using the data in the files to code up the schema.

The aim is to make sure all existing data subscribes to a pattern.
If I added the field to the schema and your "abbreviation" data does not make it into the repo, then there would be no reason for it to exist in the schema in the first place

After I have pushed the change, feel free fork and push a change like that and if @guidokessels likes it, then that is good with me.

You may also prefer to create a PR where you add those abbreviations into the data files.
If you do that and it gets merged to master before I finish my "work", then I will add it to the schema

**Comment by guidokessels** [comment]
@kingargyle I have a listed of aliases (and common misspellings) that I use in my Chrome extension. I copy-pasted it into a gist for you: https://gist.github.com/guidokessels/5e895c4e5cd882ceb4df57c56fda9cce (note: it's not update with the latest Wave 10 cards yet)

**Comment by kingargyle** [comment]
@guidokessels thanks.   This is close but is missing the link between the xws-data name and what the abbreviation would be.   I'm looking at it for people that use XStreamer, and need to output squad lists in space that is limited.   I've got a work in progress that generates Stele TV style overlays, but it uses the full name which can cause some potential issues with limited screen space.   So wanted a way to give a short name abbreviation for the same item.

**Comment by guidokessels** [comment]
I'm closing this issue as the schemas got merged.
