### ISSUE TITLE
Title for ship

### ISSUE THREAD

**Issue by cmveas** [guidokessels/xwing-data#203]
Sorry for raising the issue, probably its information that I dont know how to find but, How do I know that the ship accepts a "title".

Like "Black One" for T-70

**Comment by guidokessels** [comment]
You'll have to search `upgrades.js` for any upgrade that has the name of the ship in its `ship` property.

Here's the entry for [`Black One`](https://github.com/guidokessels/xwing-data/blob/master/data/upgrades.js#L2831-L2843):
```json
  {
    "text": "After you perform a boost or barrel roll action, you may remove 1 enemy target lock from a friendly ship at Range 1. You cannot equip this card if your pilot skill is \"6\" or lower.",
    "name": "Black One",
    "xws": "blackone",
    "unique": true,
    "points": 1,
    "slot": "Title",
    "ship": [
      "T-70 X-wing"
    ],
    "id": 244,
    "image": "upgrades/Title/black-one.png"
  }
```

As you can see it has `T-70 X-wing` in the `ship` list.

**Comment by cmveas** [comment]
thanks for taking the time to write the response. Let me know if there is any way I can help for 2.0

**Comment by guidokessels** [comment]
> Let me know if there is any way I can help for 2.0

There's information on how you can help in this post: https://github.com/guidokessels/xwing-data/issues/202#issuecomment-391493909
