### ISSUE TITLE
suggestion: condition cards

### ISSUE THREAD

**Issue by randy-ja** [guidokessels/xwing-data#21]
While looking through the repo saw I that you were asking for suggestions on how to handle condition cards but i can't find it anymore. My first thought was to handle it similar to bombs where you'd have an "effect" or "assigns" field but it's not a 1:1 relationship so that probably doesn't work well.  I'm wondering if a new file is more appropriate.  Upgrades or pilots that are able to assign a condition could have an "assigns" field that maps to the name inside conditions.js or use the existing grants with `"type": "condition", "name": "I'll Show You The Dark Side"`

conditions.js:
`[
    {
        "name": "I'll Show You the Dark Side",
        "text": "...",
        "xws":  ?,
        "id": ? 
    }
]`

**Comment by guidokessels** [comment]
Hey, as they're technically not upgrades I agree that a new `conditions.js` file would be best. I'll get on it.

**Comment by guidokessels** [comment]
Here you go, let me know if this looks reasonable: https://github.com/guidokessels/xwing-data/pull/22
