### ISSUE TITLE
Interpreting the Maneuver Arrays in the .js files

### ISSUE THREAD

**Issue by nipponaihito** [guidokessels/xwing-data#38]
Hello, 

I noticed that the maneuver arrays in the .js files are arrays of arrays of integers. In the overall array, it appears that the position reflects the speed. In the inner arrays, positionally from left to right it appears that to denote the kind of maneuver and it's direction. The positions roughtly correspond to the following order: `{left turn, left bank, straight, right bank, right turn, kturn, left sloop, right sloop, left troll, right troll}` Finally, the integer itself denotes the color of the maneuver, where 0 = not present, 1 = white, 2 = green, and 3 = red. So for the entry regarding the JumpMaster 5K:

```
[[],
 [2, 2, 2, 1, 1],
 [2, 2, 2, 1, 1, 0, 1, 3],
 [0, 1, 1, 1],
 [0, 0, 1, 0, 0, 3]]
```
Interpreting this as, 
```
No 0 speed maneuvers;
Speed 1: left turn green, left turn green, straight green, right bank white, right turn white;
Speed 2: left turn green, left turn green, straight green, right bank white, right turn white, no k-turn, left sloop white, right sloop red;
Speed 3: no left turn, left bank white, straight white, right bank white;
Speed 4: no left turn, no right turn, straight white,no right bank, no right turn, kturn red
```

Obviously there are no templates for speed 4 turns or banks but the values are still there for consistency. This reflects the JM5K dial upon visual inspection. 

Am I interpreting this correctly? I'm aiming to build a model that can simulate movement of an X-Wing ship across a simulated 2d plane.

**Comment by lvisintini** [comment]
You are correct.

Each array in the overall array contains a representation of the maneuvers available to the ship at a particular speed, determined by its position in the array.
ei. ``ship.maneuvers[1]`` will provide all maneuvers available to said ship at speed 1.

The overall array may be as short as required to provide accurate data, meaning that a missing speed 'index' indicates that the ship is is not capable of such speed.

Each value in the inner array references a different maneuver depending on its index, which maps according to the following list:
```
00 = Left Turn
01 = Left Bank
02 = Straight
03 = Right Bank
04 = Right Turn
05 = Koiogran Turn
06 = Segnor's Loop Left
07 = Segnor's Loop Right
08 = Tallon Roll Left
09 = Tallon Roll Right
10 = Backwards Left Bank
11 = Backwards Straight
12 = Backwards Right Bank
```
That is a current total of 13 maneuver types.

As you guessed, values range from 0 to 3 meaning the following:
```
0 = Maneuver unavailable
1 = White maneuver
2 = Green maneuver
3 = Red maneuver
```
This inner array may also be as short as required to provide accurate data, meaning that a missing value for a particular maneuver type indicates that said maneuver is not available to that particular ship at that particular speed

As you noticed, this structure would allow you to have speed 4 turns and banks for small ships even thought it is not possible to do that.
The same happens for all values at speed 0, except ``ship.maneuvers[0][2]`` which would indicate ``Speed 0 Straight`` or ``Stationary``

But also **beware** that the ``maneuvers`` field has slightly different interpretation for **Huge** ships.

The inner arrays have up to 6 values that have the same mapping as before (even though Koiogran Turns are not possible for huge ships at the moment) , but values are only ``1``(available) or ``0`` (unavailable)

Huge ships also have the field ``maneuver_energy`` which should map exactly with all the ``1`` values in the ``maneuvers`` field, and indicate how much energy do each of those require to be performed.

**Comment by nipponaihito** [comment]
Thank you very much for your response and detailed explanation. This is very helpful. As of now I don't plan on modeling Huge ships but I will keep your advice in mind should that be required.
