### ISSUE TITLE
Idea: Normalise text fields to use markdown instead of HTML

### ISSUE THREAD

**Issue by lvisintini** [guidokessels/xwing-data#52]
1. Would remove inconsistencies of using ``<strong>`` and ``<b>`` tags.
1. Would allow for nicer text formatting (We could use list and inline images)

We could argue that it would need additional processing on any application that uses this data, but this already happens for all the [Stop] and [Focus]

**Comment by guidokessels** [comment]
Closing this issue as we're discussing the same topic in https://github.com/guidokessels/xwing-data/pull/54
