### ISSUE TITLE
Use consistent HTML

### ISSUE THREAD

**Issue by bmds** [guidokessels/xwing-data#56]
There is a mixed use of `<strong>`, `<b>`, `<em`, and `<i>` throughout the text

E.g: 
**Ion Cannon Turret** uses `<strong>` while **Cloaking Device** uses `<b>`
**Hound's Tooth** uses `<em>` while **Phantom** uses `<i>`

I've not noticed any mixed use within one piece of text. It is easy to pick up however when converting from HTML to another syntax it adds an extra wrinkle.

**Comment by guidokessels** [comment]
Thanks, it should be consistent. I'll fix it.

Just curious; What're you converting it into?

**Comment by lvisintini** [comment]
Should we use <strong><em> or <b><i>?

<b><i> are shorter and imply styling which would match the cards text styles.

<strong><em> are style agnostic and could look different depending on the platform used, but perhaps they match better the intention of using bold or italic.

**Comment by guidokessels** [comment]
@bmds Fixed! Thanks for reporting :)
