### ISSUE TITLE
Explicit unique: false 

### ISSUE THREAD

**Issue by dmcalpin** [guidokessels/xwing-data#8]
Would you be open to explicitly setting "unique:false" in pilots.js and upgrades.js, instead of not having a value.

My use-case is specific to my own app (angular app using a filter to toggle between unique, not unique and either) but it may help others to be explicit.

Let me know and i'll get a PR open.

**Comment by guidokessels** [comment]
Hi David,
I thought about this when I started but chose not to do this. It felt this'd set a precedent and I'd have to do this for all fields (like `limited`) which would make the JSON a lot bigger, and most cards wouldn't really benefit from the extra information.

**Comment by guidokessels** [comment]
What project are you working on? Feel free to add it to the [projects list](https://github.com/guidokessels/xwing-data#projects) :)

**Comment by dmcalpin** [comment]
alright, yah that makes sense, it's easy enough to work around. Once i get this thing wrapped up, ill definitely add it. Thanks for making this data available!

**Comment by guidokessels** [comment]
I'm looking forward to see what you're making! It's good to hear people are using this data :)

**Comment by guidokessels** [comment]
I'm going to close this issue. If you think it needs to be reopened feel free to do so.
