### ISSUE TITLE
Add Project

### ISSUE THREAD

**Issue by sheepeatingtaz** [guidokessels/xwing-data#83]
I'm using your project in my X-wing overlay creator: https://github.com/sheepeatingtaz/xwingoverlayer

It's still in early stages, but our store wants to start streaming stuff so I imagine it will develop quickly!

On a related note, are there plans to include images of the damage deck in the data files? I'd like to use them in the above project, but can't seem to find them anywhere!

**Comment by lvisintini** [comment]
I have scanned the images and I'm processing them (cut, resize, optimize, etc) to add them to a pull request.

**Comment by guidokessels** [comment]
@sheepeatingtaz Your project looks really interesting! Feel free to open a PR and add it to the readme :)

@lvisintini Looking forward to those images!

**Comment by guidokessels** [comment]
Closing this as project was added in https://github.com/guidokessels/xwing-data/pull/85

**Comment by lvisintini** [comment]
@guidokessels Done with the images
See PR #88
