### ISSUE TITLE
Ship Data mismatch with XWS

### ISSUE THREAD

**Issue by kingargyle** [guidokessels/xwing-data#86]
There appears to be a ship data mismatch between the Ship.json file and data produced by the Yet Another Squad builder for the ship name.

For the Tie Advance prototype, the xwing-data ship.json has the XWS reference as  **tieadvprototype** where as Yet Another Squad Builders export has it as **tieadvancedprototype**.   This is causing XStreamer to not be able to locate appropriate ship information like Shields, Hull value, and a few other pieces of information.

Not sure who is wrong, so figure I'd start here first.

**Comment by guidokessels** [comment]
Hey, thanks for creating this issue!

The correct xws id is `tieadvprototype` as seen in the XWS spec: https://github.com/elistevens/xws-spec/blob/master/README_NAMES.md

I suggest you open a new issue for YASB here: https://github.com/geordanr/xwing

**Comment by kingargyle** [comment]
Thanks will do.  I'll close this issue since it isn't an issue here.
